version: 2
jobs:
  build:
    working_directory: ~/justin-shepard.net
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - restore_cache:
          key: modules-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install
          command: yarn install --frozen-lockfile
      - save_cache:
          key: modules-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: yarn webpack
  deploy:
    working_directory: ~/justin-shepard.net
    steps:
      - run:
          name: install aws
          command: pip install awscli --upgrade --user
      - run:
          name: s3 sync
          command: aws s3 sync dist/ s3://justin-shepard.net/
