version: 2
jobs:
  build:
    working_directory: ~/justin-shepard.net
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - restore_cache:
          key: modules-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install
          command: yarn install --frozen-lockfile
      - save_cache:
          key: modules-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: yarn flow
      - run:
          name: build
          command: yarn webpack
      - persist_to_workspace:
          root: .
          paths: dist
  deploy:
    working_directory: ~/justin-shepard.net
    docker:
      - image: circleci/python:3.6.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: install aws
          command: pip install awscli --upgrade --user
      - run:
          name: s3 sync
          command: ~/.local/bin/aws s3 sync dist/ s3://justin-shepard.net/
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
