version: 2.1

orbs:
  node: circleci/node@5.1.0
  aws: circleci/aws-cli@4.0.0

jobs:
  build:
    working_directory: ~/justin-shepard.net
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths: dist
  test:
    working_directory: ~/justin-shepard.net
    docker:
      - image: mcr.microsoft.com/playwright:v1.37.0-jammy
    steps:
      - checkout
      - node/install-packages
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: |
            npm run ci:lint
            npm run test:acceptance
      - store_test_results:
          path: reports
  deploy:
    working_directory: ~/justin-shepard.net
    executor: aws/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Sync to s3 bucket
          command: |
            aws s3 sync --exclude "*.html" --exact-timestamps --cache-control min-age=0,max-age=43200 dist/ s3://justin-shepard.net/
            aws s3 sync --exclude "*" --include "*.html" --exact-timestamps --cache-control max-age=0,no-cache,no-store,must-revalidate dist/ s3://justin-shepard.net/
workflows:
  build-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
