version: 2.1
jobs:
  build:
    working_directory: ~/justin-shepard.net
    docker:
      - image: cimg/node:18.17.1
    steps:
      - checkout
      - restore_cache:
          name: Restore dependencies cache
          key: v1-dependencies-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save dependencies cache
          key: v1-dependencies-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - ~/.cache/yarn
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: .
          paths: dist
  test:
    working_directory: ~/justin-shepard.net
    docker:
      - image: mcr.microsoft.com/playwright:v1.37.0-jammy
    steps:
      - checkout
      - restore_cache:
          name: Restore dependencies cache
          key: v1-dependencies-cache-{{ checksum "yarn.lock" }}
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: |
            yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
            yarn ci:lint
            yarn playwright test
      - store_test_results:
          path: reports
  deploy:
    working_directory: ~/justin-shepard.net
    docker:
      - image: cimg/python:3.8.4
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install AWS
          command: pip install awscli --upgrade --user
      - run:
          name: Sync to s3 bucket
          command: |
            ~/.local/bin/aws s3 sync --exclude "*.html" --exact-timestamps --cache-control min-age=0,max-age=43200 dist/ s3://justin-shepard.net/
            ~/.local/bin/aws s3 sync --exclude "*" --include "*.html" --exact-timestamps --cache-control max-age=0,no-cache,no-store,must-revalidate dist/ s3://justin-shepard.net/
workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
