// flow-typed signature: 6b6c5732117d0faeeecb09cd0a93b4c2
// flow-typed version: <<STUB>>/nightwatch-api_v1.0.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nightwatch-api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nightwatch-api' {
  declare type Expect = {
    be: Expect,
    before: (number) => Api,
    contain: (string) => Expect,
    element: (string) => Expect,
    not: Expect,
    present: Expect,
    text: Expect,
    to: Expect,
    visible: Expect,
  }

  declare type Api = {
    click: (string) => Promise<Api>,
    expect: Expect,
    setValue: (string, string) => Promise<Api>,
    url: (string) => Promise<Api>,
  }

  declare export var client: Api

  declare type NightwatchApiOptions = {|
    configFile?: string,
    env?: string,
  |}

  declare export var createSession: (env: string) => Promise<Api>;
  declare export var closeSession: () => Promise<Api>;
  declare export var startWebDriver: (env: string) => Promise<Api>;
  declare export var stopWebDriver: () => Promise<Api>;
}
