export const buzzwords: string
export const companyHeader: string
export const companySummary: string
export const details: string
export const detailsHeader: string
export const detailsList: string
export const resume: string
export const section: string
export const sectionHeader: string
